#ifndef FFF_NOMBRESDETIPOSCUADRUPLAS_H
#define FFF_NOMBRESDETIPOSCUADRUPLAS_H

typedef enum nombreDeOperador {
	SUMA_ENTERO,
	SUMA_REAL,
	RESTA_ENTERO,
	RESTA_REAL,
	MULT_ENTERO,
    MULT_REAL,
    DIV_ENTERA_ENTEROS,
    DIV_ENTERA_REALES,
    DIV_REAL_ENTEROS,
    DIV_REAL_REALES,
    MOD_ENTERO,
    ENTERO_TO_REAL,
    REAL_TO_ENTERO,
    ASIGNACION_REAL,
    ASIGNACION_ENTERA,
    ASIGNACION_BOOLEANA,
    Y,
    O,
    NO,
    MENOR,
    MENOR_O_IGUAL,
    MAYOR,
    MAYOR_O_IGUAL
} NombreDeOperador;

#endif
